### ISSUE TITLE
WebM video display problem 

### ISSUE THREAD

**Issue by duanwalker** [readium/readium-js-viewer#324] opened 2015-04-21 13:59 UTC
per Sergey Almazov:
![continuous](https://cloud.githubusercontent.com/assets/7536426/7253801/f4f32f12-e80c-11e4-9edb-4e095d31fb76.PNG)
![auto](https://cloud.githubusercontent.com/assets/7536426/7253804/f6f6fb4a-e80c-11e4-8af8-495fc98a93b3.PNG)

Chrome Extension
Win 8.1

When the scroll mode set on auto only WebM video(video-010) is working properly, the rest(video-020 - video-080 are white and are not responding.
Any change to the scroll mode(continuous or document) fixes the problem.

**Comment by duanwalker** [comment] 2015-04-21 14:01
not sure, but this may be related to issue #315

**Comment by danielweck** [comment] 2015-04-21 19:00
Thanks!
Duplicate of: https://github.com/readium/readium-js-viewer/issues/265

**Closed by danielweck** 2015-04-21 19:00 UTC
