### ISSUE TITLE
Readium cutting off page content

### ISSUE THREAD

**Issue by thiagoeec** [readium/readium-js-viewer#344] opened 2015-05-23 22:50 UTC
I'm facing an issue that seems like a bug in Readium for Chrome app.

The facts:

1) I've recently noticed that Readium app for chrome is cutting off page content near the margins.
It happens as you go through the chapter (a separated html file). The more you advance, the more the cut-off area increases. See an example page rendered (look at the left side):

![chrome-app](https://cloud.githubusercontent.com/assets/12530711/7785944/40e4a9de-0183-11e5-8c60-1a8355268834.jpg)

2) When I opened the same book in Readium Cloud Reader, it renders correctly, without cutting off the marginal area. See the rendered page:

![cloud-reader](https://cloud.githubusercontent.com/assets/12530711/7785956/9f9e4c14-0183-11e5-9522-d064457a9a55.jpg)

3) Also, I can't activate Fullscreen mode in the Chrome app.

My system:
- OS: Windows 8.1
- Chrome Version: 43.0.2357.65 m (64-bit)
- Readium app version: 2.18.1

**Comment by rkwright** [comment] 2015-05-23 23:20
@thiagoeec  Thank you for reporting this.  It appears that you were testing with Matt Garrish's Accessible EPUB, correct?  I can reproduce this sometimes, but it takes some fiddling with the window size.  I'm not seeing the "clipping increases through the book".  It seems about the same to me. Just a few pixels.
In any case, it is definitely a bug.  We will take a look.

**Comment by thiagoeec** [comment] 2015-05-24 10:59
@rkwright Thanks for looking into it.

About your comment:

1) Yes. It is Matt Garrish's <cite>Acessible EPUB3</cite>. I used it just to be sure it wasn't some styling error, since it was also available in the cloud reader library and could be tested by others than me.

2) This error <strong>aways</strong> occurs when the app window is maximized, as in the pictures below. It <em>may</em> or <em>may not</em> occur with other window sizes.

3) The clipping is surely increasing, as you can see from the samples below. I suggest you look at the "W" letters on the left side. In the third "page" of the chapter, it renders like this:

![third-page](https://cloud.githubusercontent.com/assets/12530711/7787574/27c17af6-01ea-11e5-92b9-8995e5ec61dd.jpg)

Then, in the fifth "page", it renders like this:

![fifth-page](https://cloud.githubusercontent.com/assets/12530711/7787577/3901bfc4-01ea-11e5-8c2d-45381426890f.jpg)

See that the clipping increases a bit. A bigger part of the letter "W" was cutted-off.


<strong>IMPORTANT:</strong> Don't forget about my third point on the first post. The "Fullscreen button" is not working.

**Comment by danielweck** [comment] 2015-07-11 07:44
Duplicate of: https://github.com/readium/readium-shared-js/issues/181
Pull request: https://github.com/readium/readium-shared-js/pull/188

**Closed by danielweck** 2015-07-11 07:44 UTC
Labels: bug, ReadiumJS

**Comment by SyntaxError7** [comment] 2015-12-06 16:36
I was also able to replicate this with a CCDA 640-864 Official Cert Guide. epub from ciscopress. 

Only happens in full screen mode. win7 1080 resolution

![image](https://cloud.githubusercontent.com/assets/1176677/11614331/8c46f9e8-9c0d-11e5-9d05-858b02cadaa4.png)

fullscreen:

![image](https://cloud.githubusercontent.com/assets/1176677/11614332/98f6dbc2-9c0d-11e5-9f75-13d9f17474f7.png)

**Comment by danielweck** [comment] 2015-12-07 09:47
@thiagoeec I filed a separate issue for the fullscreen bug: https://github.com/readium/readium-js-viewer/issues/442
