### ISSUE TITLE
All Highlights are on the first page

### ISSUE THREAD

**Issue by AlexeyRozhkov** [readium/readium-js-viewer#645] opened 2017-09-07 15:21 UTC
#### This issue is a Bug

Hello! Thank you for such great library, but I think I have an issue with highlights.

When we have EPUB with several virtual pages (in one html), highlights are correct redered only on a first page. When we go to next virtual page and select text, highlight is not rendered. Than we go back to first virtual page and see rendered highlight in a wrong place.

I attached screenshoots: 
First: select and highlight on a first page - OK

![h1](https://user-images.githubusercontent.com/31737698/30170817-cb977782-93f8-11e7-95f7-a8a9ee1d9502.jpg)

Second: select and NOT highlight on a second page - WRONG

![h2](https://user-images.githubusercontent.com/31737698/30170815-cb90cc98-93f8-11e7-8429-40c3390cd02a.jpg)

Thired: go back to the first page and see wrong highlights - WRONG

![h3](https://user-images.githubusercontent.com/31737698/30170816-cb9280b0-93f8-11e7-8389-ebf75cb52d90.jpg)

### Product
Readium JS viewer with highlight plugin.

Maybe I do something wrong...
Can you help me please? Thank you!

**Comment by danielweck** [comment] 2017-09-07 15:55
Hello, thank you for your feedback!
What revision / branch are you using?
What web browser?

**Comment by AlexeyRozhkov** [comment] 2017-09-07 19:36
Hello, Daniel
Thank you for quick answer!
I'm using the last revision, master branch. Labels: 0.27.0. Your last commit is [921cd45] from 12/06/2017. 
The same behaviour for Chrome, IE and all mobile browers. Chrome version 60.0.3112.113 (64-bit).

**Comment by AlexeyRozhkov** [comment] 2017-09-08 07:40
I figured out what has happened.

When highlight renders it is got wrong pageOffset. 

In highlight controller I found this line:

`offset = this.context.paginationInfo.pageOffset;`

And offset is indefined.

But when context is created I found function and not a property. 
Highlight manager.js -> this.attachAnnotations = function

`paginationInfo: function() { return spineItem.paginationInfo; }`

I replaced it with:

`paginationInfo: spineItem.paginationInfo`

Now it is OK. 
But maybe I don't understand the whole thing. Maybe you will check it. :)
Thank you!

**Comment by danielweck** [comment] 2017-09-08 08:42
Hello @JCCR this looks like a regression bug from:
https://github.com/readium/readium-shared-js/commit/9967855c46802672bedd57d3c12056683705075c#diff-6d1424ffdf1e073d51d72f6fc7de7464R556

(note that all other usage of `paginationInfo` in the source tree is correct, i.e. as a property, not a getter function)

https://github.com/readium/readium-shared-js/blob/05be48df7021bda38147ba38e9855c2ab2965ebe/plugins/highlights/controller.js#L557-L561

https://github.com/readium/readium-shared-js/blob/05be48df7021bda38147ba38e9855c2ab2965ebe/plugins/highlights/manager.js#L117

**Comment by danielweck** [comment] 2017-09-08 08:48
Fixed via https://github.com/readium/readium-shared-js/commit/efa5ea5ed4e848b761774172ce6cd95cb2d82d82

Thank you very much @AlexeyRozhkov !!

**Closed by danielweck** 2017-09-08 08:48 UTC
