### ISSUE TITLE
Readium will not load book in IE

### ISSUE THREAD

**Issue by davedmiller** [readium/readium-js-viewer#450] opened 2016-01-04 21:45 UTC
The following epub file (shared from my google drive, https://drive.google.com/file/d/0B1Z_NtQWtWCDNG03eEZETFhqdnc/view?usp=sharing) does not load in readium (2.23.0-alpha, develop branch) under IE v.11.20.10586.0. It sits forever spinning the circle of dots...

I have run this epub through the validator at: http://validator.idpf.org/ with no errors. The file loads in readium on Chrome v47, Edge v25, and Firefox v40. All work was done on Windows 10 Pro.

I am running per instructions found on github page at https://github.com/readium/readium-js-viewer. I cloned the 'develop' branch and issued command 'npm run http'

Here is a screenshot of the console after a refresh of IE v 11

![image](https://cloud.githubusercontent.com/assets/689057/12101399/5aae8d2c-b2e9-11e5-997c-455d3628469d.png)

This is not the only book we have assembled that passes the validator and has this issue. If you could advise either a work around for our books, or suggest a fix for readium it would be appreciated.

**Comment by danielweck** [comment] 2016-01-07 11:01
I am able to successfully read the "SecretSistersSneakPeek" ebook on my Windows 10 machine (Internet Explorer, Edge, Firefox, and Chrome), using the exploded / unzipped EPUB, e.g.:
http://127.0.0.1:8080/dev/index_RequireJS_no-optimize.html?epub=..%2Fepub_content%2FSecretSistersSneakPeek

However, the packed EPUB fails to load in Internet Explorer (works fine in Edge, Firefox and Chrome):
http://127.0.0.1:8080/dev/index_RequireJS_no-optimize.html?epub=..%2Fepub_content%2FSecretSistersSneakPeek.epub

I am going to look into this issue, but please note that loading zipped EPUB directly introduces a number of caveats (some of which critical, for example if you need support for video/audio media playback). Generally-speaking, the recommended EPUB deployment strategy is to unzip / expand / explode content on the server.

**Comment by danielweck** [comment] 2016-01-07 11:45
The issue is related to empty `title` elements in the HTML `head`, when XML-parsed (for XHTML DOM processing). Some time ago there was a similar problem in native launcher apps (UIWebView)
Fixed by replacing empty titles with "something":
https://github.com/readium/readium-js/commit/2747c8f169595c668d89bce038af619d1946989a

**Closed by danielweck** 2016-01-07 11:45 UTC
