### ISSUE TITLE
blinking video in firefox

### ISSUE THREAD

**Issue by duanwalker** [readium/readium-js-viewer#302] opened 2015-03-18 19:34 UTC
when launching the video player, some tests in the spread begin to disappear and reappear. this happens sporadically in firefox when testing 
![4 blinking after video launch even with toc](https://cloud.githubusercontent.com/assets/7536426/6717606/2386c0f8-cd84-11e4-9943-e35aeb952195.PNG)
![3 same pages show up after toc open](https://cloud.githubusercontent.com/assets/7536426/6717605/2385f772-cd84-11e4-8e2d-49d2df852779.PNG)

epubtest-0100: audio-010, 020, 030, video-010 to 080, trigger 010 to 040
140: epubcfi-030, 040, 050

**Comment by duanwalker** [comment] 2015-03-18 19:35
note: the first image is after it has started blinking, the second image should be first as it is beginning to play the video

**Comment by danielweck** [comment] 2015-03-19 06:46
Thanks Duan, it looks like not only Chrome is affected by CSS-Column + video rendering bugs, but also Firefox. I will see if my "official" Chromium test sample (as submitted to the Google team) can be used to reproduce the issue consistently on Firefox too.

**Comment by danielweck** [comment] 2015-03-19 09:08
**Update**
The Chromium test case does not trigger the "blinking video" bug in Firefox:
https://code.google.com/p/chromium/issues/detail?id=458520
http://www.daisy.org/projects/tobi/VideoCSSColumns/

However, I created a new test-case that does trigger the bug consistently (CSS columns display fine in Chrome, but start blinking in Firefox as soon as the video plays). I'm trying to find a CSS workaround. In the meantime, here is the test sample:
http://www.daisy.org/projects/tobi/videoCSSColumns_Firefox/
(technical note: this is due to the CSS width on the HTML element, which has to be set equal to a single page width otherwise the columns do not display with the correct width, on Firefox, Chrome, etc.)

**Comment by danielweck** [comment] 2015-03-19 20:01
@jdempcy suggested to use CSS column *count* (1 or 2) with a fixed HTML width equal to the full viewport / iframe width, instead of  CSS column *width* with an HTML width equal to half the viewport (in the case of a 2-page synthetic spread). I tried, this solves the Firefox video flickering bug, but does not fix the Chrome video rendering / interaction bugs.

**Comment by danielweck** [comment] 2015-03-19 21:39
Addressed in "fix" branch: https://github.com/readium/readium-shared-js/tree/fix/css-columns
https://github.com/readium/readium-shared-js/commit/a281a78663fcdf409333c55883cb1c7b7000203b
commit message:
```
using column-fill:auto to prevent Firefox from automatically balancing content (which means the height hack isn't needed anymore), more importantly: column-count is used for two-page synthetic spreads, but column-width still used for single-page layout (for some weird CSS reason, we need this discrepancy in Chrome)
```

**Comment by danielweck** [comment] 2015-03-19 21:58
@jdempcy would you be so kind as to testing my fix in your iOS launcher app? Please try portrait/landscape aspect ratios, and force-switch from single to two-page synthetic spread (regardless of the device orientation).

**Comment by jdempcy** [comment] 2015-03-19 22:11
Sure! Happy to do so now. Will follow up presently.

--
Jonah Dempcy
T 206.226.2857 | E jdempcy@gmail.com
Follow on Facebook <https://www.facebook.com/jdempcy> | @jdempcy
<http://www.twitter.com/jdempcy> | /in/jdempcy
<http://htmlsandbox.com/www.linkedin.com/in/jdempcy>

**Comment by jdempcy** [comment] 2015-03-19 22:27
At first I got a JS error due to the recent change where we removed version numbers from filenames:
[Error] Failed to load resource: The requested URL was not found on this server. (jquery-1.11.0.js, line 0)

So I changed the <script> include to jquery.js instead of jquery-1.11.0.js.

This fixed the error and I was able to test. 

iPad 2 simulator portrait mode (single column off):
![image](https://cloud.githubusercontent.com/assets/95693/6742318/0b3486b6-ce4c-11e4-9e23-fbfdfc5f01b7.png)

iPad 2 simulator portrait mode (single column on):
![image](https://cloud.githubusercontent.com/assets/95693/6742324/19665e62-ce4c-11e4-9507-c824f1acc342.png)

iPad 2 simulator landscape mode (single column off):
![image](https://cloud.githubusercontent.com/assets/95693/6742337/3614d61a-ce4c-11e4-819c-4b97342c03a0.png)

iPad 2 simulator landscape mode (single column on):
![image](https://cloud.githubusercontent.com/assets/95693/6742333/268a8cc6-ce4c-11e4-8606-957bce008470.png)

I'm not sure if our app has the ability to automatically select single or two-page synthetic spreads—I believe it simply follows the user setting. When the 'Single Column Text' setting is set to true, all books render in single column spreads, which when it is set to false, they render in two-page spreads.

**Comment by jdempcy** [comment] 2015-03-19 22:29
In any case, it looks fine to me in our (modified) version of the SDKLauncher-iOS app!

**Comment by danielweck** [comment] 2015-03-19 22:40
Thanks @jdempcy the jQuery lib naming convention was fixed in the develop branch:

https://github.com/readium/SDKLauncher-iOS/commits/develop

https://github.com/readium/SDKLauncher-iOS/commit/26bfd0c2ccfbaf9445509ab80908baf251729077

**Comment by danielweck** [comment] 2015-03-24 16:18
Fixed: https://github.com/readium/readium-shared-js/pull/169

**Closed by danielweck** 2015-03-24 16:18 UTC
