### ISSUE TITLE
NPM build process, semantic versioning on external dependencies, bind to major versions

### ISSUE THREAD

**Issue by danielweck** [readium/readium-js-viewer#432] opened 2015-11-10 18:14 UTC
Master (or any other branch) should never break as a result of a breaking change in an external dependency's major update (assuming semantic versioning is used correctly by those external Javascript libraries, of course). Right now, because we reference the _latest_ version instead of "the latest for a given major revision", we expose ourselves to the possibility of broken builds. Like here:
https://github.com/readium/readium-js-viewer/issues/431

**Comment by danielweck** [comment] 2016-01-07 11:03
Yet another example: https://github.com/readium/readium-cfi-js/pull/44

**Comment by danielweck** [comment] 2016-09-13 12:35
Related issue: https://github.com/readium/readium-js-viewer/issues/565

**Comment by da70** [comment] 2016-12-07 17:00
We recently set up an in-house build system for our version of ReadiumJS viewer, in part to make sure we could guarantee a reliably reproducible build with locked versions.  We have a custom plugin and anticipate a lot more plugin development so it was important that we stabilize our instances.

Past experience had shown that `npm shrinkwrap` was incapable of generating lock files for `readium-js` and `readiums-shared-js`.  We came up with a complicated build system that involved saving a tarzip'ed snapshot of the production `readium-js-viewer` repo and sub-modules with all `node_modules/`, and also "borrowing" `.git` directories from a separate clone at build time due to `npm run dist` needing to do git operations.
It's clunky, though, and a single snapshot at `bzip2 -9` compression is 120MB+.

Shortly after we finished, this came out: [Yarn: A new package manager for JavaScript](https://code.facebook.com/posts/1840075619545360).  Yarn was built by Facebook, Google, and a couple other partners.  Note that since this article was written it is now possible to install yarn standalone as opposed to (ironically) an NPM module.

This week we were able to get around testing it with ReadiumJS viewer, and were able to install all dependencies, lock module versions, and successfully build a `cloud-reader`.  Occasionally we had to run `yarn` twice in a repo, as an error would appear in a first pass and would apparently be fixed in the second.  Nevertheless, these steps were basically all it took to switch an existing `readium-js-viewer` instance from npm to yarn (note that #356 had to be manually fixed first):

```shell
rm -fr node_modules/ readium-js/node_modules/ readium-js/readium-shared-js/node_modules/ readium-js/readium-shared-js/readium-cfi-js/node_modules/
yarn
cd readium-js/
yarn
cd readium-shared-js/
yarn
cd readium-cfi-js/
yarn
cd ../../../
npm run prepare
npm run dist
```

The `npm run prepare` step is necessary to avoid this error during `npm run dist`:

```shell
Error: Error: ENOENT: no such file or directory, open '/Applications/MAMP/htdocs/readium-js-viewer/readium-js/readium-shared-js/node_modules/eventemitter3/_rjs/index.js'
    at Object.fs.openSync (fs.js:557:18)
```

I diff'ed the yarn-generated `node_modules/` and npm-generated `node_modules/` and found no significant differences.  Most of the variation was due to yarn being able to more intelligently flatten the dependency tree.  It knew when a module that another module required was already installed at top-level, and wouldn't install a duplicate nested within the requiring module, whereas npm apparently thought it was necessary to install another copy when it wasn't in fact needed.
Also, yarn created files called `node_modules/yarn.integrity` that contain hashes for the `node_modules/` directories, which yarn then used to verify that nothing had been changed, corrupted, hacked, etc.

The resulting `cloud-reader/` passed our tests in Chrome and Firefox.  We are going to move forward with using yarn to lock our dependencies.

Just thought I'd share this.  If Readium thinks yarn would be a viable option, maybe a note could be put into the `README.md` for people who are looking for a quick solution to locking.  If desired, the various `prepare:*` scripts could be changed to use yarn, and yarn itself could be included in the project as an NPM module so that users would not have to install it themselves.  That would also guarantee yarn version compatibility (avoiding problems such as the NPM v3 bug with peer dependencies).  There could be separate `prepare` scripts for locked-dependencies versions and for latest-dependencies versions.  I suppose there would need to be separate `dist` scripts, too.

**Comment by da70** [comment] 2017-01-05 20:49
Have attempted to update our builder using yarn lockfiles.  Turns out the `npm run prepare` is a no-go because it runs this:

```json
    "prepare:local": "npm outdated && npm install && npm update && node readium-js/readium-shared-js/readium-cfi-js/readium-build-tools/gitHubForksUpdater.js",
```

`npm outdated` will always return true because of Github dependencies:

```shell
$ npm outdated
Package                         Current  Wanted  Latest  Location
bootstrap-accessibility-plugin    1.0.5     git     git  bootstrap-accessibility-plugin
http-server                       0.9.0     git     git  http-server
jath                              0.0.3     git     git  jath
keymaster                         1.6.3     git     git  keymaster
```

...and so `npm update` will always run.  Could that a `npm-shrinkwrap.json` file would keep `npm outdated` from flagging these, but since it's not aware of the `yarn` lockfile, it goes ahead with its outdated report.

For now, am working around it by manually running the other, non-module-updating parts of `npm run prepare`.

**Comment by da70** [comment] 2017-01-31 20:25
Copying from [comment in #601](https://github.com/readium/readium-js-viewer/issues/601#issuecomment-276480587), in case it's useful to anyone in the interim:

> We've been able to successfully lock our Readium instance using [yarn](https://yarnpkg.com/).  If you want to take a look, go to [dlts-readium-js-viewer](https://github.com/NYULibraries/dlts-readium-js-viewer) and check out [the yarn.lock files](https://github.com/NYULibraries/dlts-readium-js-viewer/tree/master/lockfiles/prod) for each Readium project (one in each sub-directory).  The [build script](https://github.com/NYULibraries/dlts-readium-js-viewer/blob/master/scripts/dist.sh) is in Bash and shows the commands you would run on the command line to build a locked-version reader.  It's pretty simplistic, but it works.  We do a (virtual) byte-level verification of the build, and so far there haven't been any problems.

**Comment by danielweck** [comment] 2017-11-16 20:21
Current status: NPM `package-lock.json` files are in each ReadiumJS GitHub repositories (so dependencies are effectively frozen for a given Git revision / commit hash). However, the build script(s) invoke `npm update` (not just `npm install`), which means that the lock files can potentially be updated during Continuous Integration (i.e. on Travis servers), resulting in discrepancies between local and remote builds. Furthermore, `latest` is used instead of better-practice `^a.b.c` semantic versioning. This needs fixing too. I will give this a pass.

**Comment by danielweck** [comment] 2017-11-16 20:51
`readium-cfi-js` done:
https://github.com/readium/readium-cfi-js/commit/cd076bbdc73b920a0b2cb9022c1d9d87309770a1
(`package-lock.json` re-generated from scratch, with removed `node_modules` folder to ensure clean slate)

**Comment by danielweck** [comment] 2017-11-16 20:54
`readium-shared-js` done:
https://github.com/readium/readium-shared-js/commit/d6074e3e7f1edeae85ca6b6f74b3a5e361db7b5e

**Comment by danielweck** [comment] 2017-11-16 20:58
`readium-js` done:
https://github.com/readium/readium-js/commit/728e7d302d4db5f928d443b1b4a58601bf27d6a2

**Comment by danielweck** [comment] 2017-11-16 21:01
`readium-js-viewer` done:
https://github.com/readium/readium-js-viewer/commit/2d8df17b7b38880e8daff1f11efd701ffc769af1

**Comment by danielweck** [comment] 2017-11-16 21:02
TravisCI now building:
https://travis-ci.org/readium/readium-js-viewer/builds/303221329
... let's see how it goes, now that `npm update` has been removed (as well as `yarn upgrade`), and that `package-lock.json` references exactly the same semantic versions as `package.json` (no more `latest`).

**Closed** 2017-11-16 21:08 UTC
Labels: func:Builds, priority:Medium, type:Bug, type:Enhancement
