### ISSUE TITLE
Fullscreen button not updated when entering fullscreen mode

### ISSUE THREAD

**Issue by HGuillemet** [readium/readium-js-viewer#625] opened 2017-06-07 23:40 UTC
I see in EpubReader.js that the fullscreen button is supposed to change when entering fullscreenmode (icon and tooltip). But this is not working.

### Product
* Readium cloud reader app
* Tested on Firefox and Safari

**Comment by danielweck** [comment] 2017-09-30 10:10
I am not able to reproduce this bug (OSX Safari and Chrome).
Tested with: https://readium.firebaseapp.com/?epub=epub_content%2Faccessible_epub_3&goto=%7B%22idref%22%3A%22id-id2611884%22%2C%22elementCfi%22%3A%22%2F4%2F2%5Bintroduction%5D%2F2%2F1%3A0%22%7D
Can you please provide some details? (platform, versions, etc.)

**Comment by HGuillemet** [comment] 2017-10-01 14:57
When I click on the link you provide, then on the fullscreen icon, I do enter fullscreen mode, but the icon still looks the same and the tooltip still reads "Enter fullscreen".
This happens on Firefox 52.3.0 and Safari 11.0. S

**Comment by danielweck** [comment] 2017-10-02 04:45
oh, my bad, I misread your bug description, sorry.

**Comment by danielweck** [comment] 2017-10-03 06:45
Fixed via PR: https://github.com/readium/readium-js-viewer/pull/654

**Closed by danielweck** 2017-10-03 06:45 UTC
Labels: difficulty:Dev, func:UX, priority:Medium, type:Bug
