### ISSUE TITLE
TOC does not always navigate to the correct location

### ISSUE THREAD

**Issue by rkwright** [readium/readium-js-viewer#515] opened 2016-04-06 07:12 UTC
Reported via email by Franklin Veaux:

"As long as the ToC items reference a new file inside the ePub, all is good. However, if a ToC entry   references a section within a file—a subheading, say—clicking on that Table of Contents entry goes to the wrong place in the file. For example, if I have an eBook that has section heads within a file, identified by an ID attribute on a tag, and I click on the Table of Contents to go to one of those sections, Readium will take me to what seems to be a random place within that file in the eBook.
*Make sure to fill-in as much information as possible in the sections below:"

Verified by Readium QE in Readium Chrome 2.23.0-alpha

### Related issue(s), pull request(s)

See also #NUMBER

### Expected behaviour

Should navigate to the expected location.

### Observed behaviour

Instead, goes somewhere else.

### Steps to reproduce

1. Load test file [here](https://github.com/readium/readium-test-files/tree/master/issue-files/readium-js-viewer/515)
2. Try to navigate to one the TOC entries, e.g. "Do People Choose to be Poly". 
3. It doesn't navigate to the page with that section but in fact the page before. 

Similar errors can be seen with other TOC entries.  The errors don't seem to huge - usually the next page is correct.

### Test file(s)
See above

### Product
Chrome Extension (2.22.3)

### Web browser
Chrome

### Operating system
OSX Yosemite (10.10)

### Additional information.
From Franklin Veaux:
"Attached is a sample eBook where the ToC entries do not take the reader to the correct place in Readium. I’m using Readium on Google Chrome for Mac under OS X Yosemite. The eBook was built in Calibre version 2.54.0."

**Comment by JCCR** [comment] 2016-04-07 18:02
If the iframe managed by Readium has an odd numbered width I can reproduce this bug. If it's even numbered I can't.
I just merged in https://github.com/readium/readium-shared-js/pull/200 

The reason why this happens is because the visibility checking functions get screwed up when the columns are clipped even by one pixel (which happens in this case)

**Comment by danielweck** [comment] 2016-04-11 11:37
This should be fixed by Juan's PR (see message above).
I am not able to reproduce the described bug:
https://readium.firebaseapp.com/?epub=https%3A%2F%2Frawgit.com%2Freadium%2Freadium-test-files%2Fmaster%2Fissue-files%2Freadium-js-viewer%2F515%2FWhen%2520Someone%2520You%2520Love%2520Is%2520Polyamorous%2520-%2520Elisabeth%2520Sheff.epub
(test file is https://github.com/readium/readium-test-files/tree/master/issue-files/readium-js-viewer/515 )

**Closed by danielweck** 2016-04-11 11:37 UTC
Labels: bug, priority high [critical]
