### ISSUE TITLE
MediaOverlay Issue

### ISSUE THREAD

**Issue by himanshukimni2000** [readium/readium-js-viewer#608] opened 2017-02-28 14:55 UTC
I have noticed that some of the Fixed Layout animated eBooks with Read Aloud features re-loads the pages as soon as mediaoverlay (SMIL) file gets hits for that particular  page, that means page re-loads twice as soon as the SMIL starts working. I am using Readium Chrome plug-in at my end.

Kindly review below screen-cast, so that you can get some idea what I meant to say:

Screencast: [SWF](https://drive.google.com/file/d/0BwAtEW6bmFveZkhiVmw5QXFUX0k/view?usp=sharing)
eBook: [ePub package](https://drive.google.com/file/d/0BwAtEW6bmFveTFVwTXhVYms3cjA/view?usp=sharing) 

Look forward hearing your thoughts on this.

Best wishes,
Himanshu

**Comment by rkwright** [comment] 2017-02-28 15:26
@himanshukimni2000 Thank you for your report.  We'll look into it.
@danielweck I downloaded the book and put it in the Issue files folder [here](https://drive.google.com/open?id=0BzaNaBNAB6FjU0xMWnZxOFExdzg)

**Comment by danielweck** [comment] 2017-02-28 17:00
Repro link:
https://readium.firebaseapp.com/?epub=https%3A%2F%2Fcdn.rawgit.com%2FIDPF%2Fepub-testsuite%2Fmaster%2Fcontent%2F30%2Fepub30-test-0220

**Comment by himanshukimni2000** [comment] 2017-03-03 07:23
I have noticed that if I will take the spread pages in single HTML then this re-loading issue gets resolved.

Thought sharing this might help you!

Best wishes,
Himanshu

**Comment by danielweck** [comment] 2017-03-05 11:11
duplicate of: https://github.com/readium/readium-shared-js/issues/359

**Closed by danielweck** 2017-03-05 11:11 UTC
Labels: browser:ChromeExtension, difficulty:Dev, func:Layout, func:MediaOverlay, priority:High, status:Reproducible, type:Bug
