### ISSUE TITLE
Bug: "back" navigation history with fixed-layout EPUBs (does not go back to library, blank page instead)

### ISSUE THREAD

**Issue by rkwright** [readium/readium-js-viewer#477] opened 2016-02-01 18:37 UTC
I am seeing strange OPDS navigation problems.  Go to the new site here:

http://readium.github.io/readium-js-viewer/index.html?epubs=epub_content%2Fepub_library.opds&

Open up Page Blanche, navigate forward a few pages to the first non-frontmatter page.

Now hit the browser’s back button and … nothing happens.  Or the page goes blank.  Happens to me on OSX 10.10 for Chrome, Firefox and Safari.

And at this point the url is:
http://readium.github.io/readium-js-viewer/index.html?epub=http%3A%2F%2Freadium.github.io%2Freadium-js-viewer%2Fepub_content%2Fpage-blanche&epubs=epub_content%2Fepub_library.opds&

Not surprisingly the console reports a 404 error. Still looking into it.

**Comment by danielweck** [comment] 2016-02-02 09:02
Thanks Ric, I am able to reproduce this navigation problem with the JSON library, so this is not related to OPDS (thus the title renaming, I hope you don't mind).
Furthermore, I am able to reproduce this browser history bug with any fixed layout EPUB, so this is not related to the JSON vs. OPDS library format either. For example, try "Page Blanche" using the latest reader app built from the develop branch, and served via the JSON library:
https://readium.firebaseapp.com/?epubs=epub_content%2Fepub_library.json

**Comment by danielweck** [comment] 2016-02-02 09:19
Even better: open the "Page Blanche" directly without any library `epubs` parameter in the URL:

http://127.0.0.1:8080/dev/index_RequireJS_no-optimize.html?epub=http%3A%2F%2F127.0.0.1%3A8080%2Fepub_content%2Fpage-blanche

Navigate previous / next a couple of times, and use the browser history. There seems to be unwanted insertions in the browser history.

**Comment by danielweck** [comment] 2016-02-02 10:25
@rkwright fixed-layout iframe loading is now consistent with the reflowable view: I pushed a fix in the develop branch to disable iframe "recycling" in `fixed_view` (the preservation of `one_page_view` already-used iframes is what was causing problems with navigator history and lapsed / revoked BlobURIs). I tested this change with the scroll view as well (which ; just like `fixed_view` ; uses `one_page_view`).

https://github.com/readium/readium-shared-js/commit/adcbe4a90b6cf77bed150700b77b30c366c134ea

**Comment by danielweck** [comment] 2016-02-02 10:33
Note, TravisCI build in progress: https://travis-ci.org/readium/readium-js-viewer/builds/106439028

We should be able to check the bugfix in Firebase in a few minutes...

https://readium.firebaseapp.com/?epub=epub_content%2Fpage-blanche

**Comment by danielweck** [comment] 2016-02-02 10:46
Tested at https://readium.firebaseapp.com
Closing.

**Closed by danielweck** 2016-02-02 10:46 UTC
Labels: bug, priority HIGH [blocking]
