### ISSUE TITLE
Using readium-js-viewer_all_LITE.js in IE fails

### ISSUE THREAD

**Issue by mahag** [readium/readium-js-viewer#548] opened 2016-07-14 09:03 UTC
I am using readium lite to show epub files. I noticed that on IE 10 and 11 the epub doesnt appear and it spins forever.
In developer debug it is showing this error 

> SCRIPT438: Object doesn't support property or method 'trace' 

in line where we have

> console.trace(JSON.stringify(t)),

Any fix for that? I did try with mobi-dick provided in epub_content folder

**Comment by rkwright** [comment] 2016-07-14 13:36
This does seem like a bug.  IE does support the console.trace method though note that some recommend that it not be used.  See [here](https://developer.mozilla.org/en-US/docs/Web/API/Console/trace).  But it's not clear why one would see this error.  

@mahag : Where in the code was this statement?

**Comment by mahag** [comment] 2016-07-15 06:36
![image](https://cloud.githubusercontent.com/assets/10612561/16865713/9c22d84e-4a6f-11e6-8b4f-cea3fed74d6c.png)

**Comment by danielweck** [comment] 2016-08-17 06:18
Regarding the `console.trace()` error, this should be fixed now.
Regarding the second kind of error you reported in the comment, could you please post a separate issue and clarify what the problem is exactly? (I do not understand whether this is a Readium-related issue, or whether this is a problem with IE / Edge web debugger)

**Closed by danielweck** 2016-08-17 06:18 UTC
Labels: browser:IE, func:JavaScript, platform:Windows, priority:High, type:Bug
